2025-07-22 14:20:02,407 - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2025-07-22 14:20:04,626 - INFO - Connecting to Redshift...
2025-07-22 14:20:05,113 - ERROR - Redshift load failed
Traceback (most recent call last):
  File "c:\Users\UNIQ\pythonlearning\source_code\s3_to_redshift", line 95, in <module>
    cursor.execute(create_stmt)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.InvalidTableDefinition: Cannot define relation in system schema "catalog_history"

